// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from '@prisma/config'
import path from 'path'
import dotenv from 'dotenv'

// Explicitly load the .env.local file from your root directory
dotenv.config({ path: path.resolve(process.cwd(), '.env.local') })

export default defineConfig({
  datasource: {
    url: process.env.DATABASE_URL,
  },
})